# Environment variables for cargo commands ONLY
# For deployment environment variables, use .env file or container management tools

[env]
#RUST_BACKTRACE="1"

RUST_LOG="webapi=debug"

# -- SECRETS
SERVICE_DB_URL="postgres://app_user:dev_only_pwd@localhost:5434/app_db"

SERVICE_PWD_KEY="0Cgvkf2QldDAXYVS7LN2bs3ckKIPWJKQi3KY4CqlJTV9ys18YwMV0SmBN0HTj-uOqH50M3oIEgp1YcgMmjIFVg"

SERVICE_TOKEN_KEY="epN_8kQxK-8JnBTOwxTQpXa0Rno77Qr08-RYmAQYTLtmY9ieJcV4By57tLC3K-V6R1Sd2dOAXPJI-vOuzgBZ2Q"
SERVICE_TOKEN_DURATION_SEC="1800" # 30 minutes

# -- CONFIGURATION
SERVICE_WEB_FOLDER="web-folder/"
